<#
.SYNOPSIS
    Pester 5 lab tests for all 15 IR Toolkit mwcp parsers.

    Validates the full end-to-end pipeline:
      parser_config.yml registration -> mwcp_scan.py -> JSON output

    Synthetic TP/FP samples are generated by generate_samples.py once.
    Tests skip automatically when mwcp is not staged in tools/.
#>

BeforeAll {
    $script:Root    = Resolve-Path (Join-Path $PSScriptRoot "..\..\..")
    $script:WinHunt = Join-Path $script:Root "playbooks\windows\threat_hunting"
    $script:MwcpScan = Join-Path $script:WinHunt "mwcp_scan.py"
    $script:MwcpLib  = Join-Path $script:Root "tools\mwcp\lib"
    $script:LabDir   = $PSScriptRoot
    $script:Generate = Join-Path $script:LabDir "generate_samples.py"
    $script:TP       = Join-Path $script:LabDir "samples\tp"
    $script:FP       = Join-Path $script:LabDir "samples\fp"

    # Find Python: bundled (memprocfs embed) first, then system
    $script:Python = $null
    $bundledPy = Join-Path $script:Root "tools\memprocfs\python\python.exe"
    if (Test-Path $bundledPy) { $script:Python = $bundledPy }
    if (-not $script:Python) {
        $sys = Get-Command python -ErrorAction SilentlyContinue
        if ($sys) { $script:Python = $sys.Source }
    }
    if (-not $script:Python) {
        $sys = Get-Command python3 -ErrorAction SilentlyContinue
        if ($sys) { $script:Python = $sys.Source }
    }

    $script:MwcpAvailable = (
        $null -ne $script:Python -and
        (Test-Path $script:MwcpLib) -and
        (Test-Path $script:MwcpScan)
    )

    # Generate lab samples if not present
    if ($script:MwcpAvailable) {
        $tpProbe = Join-Path $script:TP "cobalt_strike.bin"
        if (-not (Test-Path $tpProbe)) {
            & $script:Python $script:Generate | Out-Null
        }
    }

    function script:Invoke-MwcpScan {
        param([string]$FilePath)
        if (-not $script:MwcpAvailable) { return $null }
        $raw = & $script:Python $script:MwcpScan $script:MwcpLib '-' $FilePath 2>$null
        if (-not $raw) { return $null }
        try { return ($raw | ConvertFrom-Json)[0] } catch { return $null }
    }

    function script:Has-IOC {
        param($r)
        if ($null -eq $r) { return $false }
        return (($r.address -and $r.address.Count -gt 0) -or
                ($r.mutex   -and $r.mutex.Count   -gt 0) -or
                ($r.password -and $r.password.Count -gt 0) -or
                ($r.decoded -and $r.decoded.Count  -gt 0))
    }

    function script:Get-AllText {
        param($r)
        if ($null -eq $r) { return '' }
        $parts = @()
        @('address','mutex','password','decoded') | ForEach-Object {
            if ($r.$_) { $parts += $r.$_ }
        }
        return $parts -join ' '
    }
}

# ---------------------------------------------------------------------------
# Skip guard -- all remaining tests inherit this
# ---------------------------------------------------------------------------
Describe "mwcp parser lab -- environment check" {
    It "Should have mwcp staged and Python available to run parser lab tests" {
        if (-not $script:MwcpAvailable) {
            Set-ItResult -Skipped -Because "mwcp not staged in tools/ or Python not found"
        }
        $script:MwcpAvailable | Should -Be $true
    }
}

# ===========================================================================
# TP TESTS -- each parser must extract at least one IOC from its sample
# ===========================================================================
Describe "TP: CobaltStrikeConfig" {
    BeforeAll { $script:csResult = Invoke-MwcpScan (Join-Path $script:TP "cobalt_strike.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract at least one IOC from the CS config block" {
        Has-IOC $script:csResult | Should -Be $true
    }

    It "Should contain [CS-Config] in decoded output" {
        $t = Get-AllText $script:csResult
        $t | Should -Match 'CS'
    }
}

Describe "TP: SliverConfig" {
    BeforeAll { $script:sliverResult = Invoke-MwcpScan (Join-Path $script:TP "sliver_implant.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract at least one IOC" {
        Has-IOC $script:sliverResult | Should -Be $true
    }

    It "Should contain mtls:// transport scheme in output" {
        $t = Get-AllText $script:sliverResult
        $t | Should -Match 'mtls://'
    }
}

Describe "TP: HavocConfig" {
    BeforeAll { $script:havocResult = Invoke-MwcpScan (Join-Path $script:TP "havoc_daemon.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract at least one IOC from 0xDEADBEEF config block" {
        Has-IOC $script:havocResult | Should -Be $true
    }
}

Describe "TP: BruteRatelConfig" {
    BeforeAll { $script:brc4Result = Invoke-MwcpScan (Join-Path $script:TP "brute_ratel.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract at least one IOC" {
        Has-IOC $script:brc4Result | Should -Be $true
    }

    It "Should contain pipe name in decoded output" {
        $t = Get-AllText $script:brc4Result
        $t | Should -Match 'ratel|pipe'
    }
}

Describe "TP: MythicConfig" {
    BeforeAll { $script:mythicResult = Invoke-MwcpScan (Join-Path $script:TP "mythic_agent.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract PayloadUUID or C2 address" {
        Has-IOC $script:mythicResult | Should -Be $true
    }
}

Describe "TP: MerlinConfig" {
    BeforeAll { $script:merlinResult = Invoke-MwcpScan (Join-Path $script:TP "merlin_agent.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract PSK or C2 URL" {
        Has-IOC $script:merlinResult | Should -Be $true
    }
}

Describe "TP: PoshC2Config" {
    BeforeAll { $script:poshResult = Invoke-MwcpScan (Join-Path $script:TP "posh_c2.ps1") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract server URL" {
        Has-IOC $script:poshResult | Should -Be $true
    }

    It "Should contain c2.lab.test in output" {
        $t = Get-AllText $script:poshResult
        $t | Should -Match 'c2\.lab\.test'
    }
}

Describe "TP: NjRATConfig" {
    BeforeAll { $script:njratResult = Invoke-MwcpScan (Join-Path $script:TP "njrat_config.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract C2 address with port 4444" {
        $t = Get-AllText $script:njratResult
        $t | Should -Match '4444'
    }
}

Describe "TP: AsyncRATConfig" {
    BeforeAll { $script:asyncResult = Invoke-MwcpScan (Join-Path $script:TP "asyncrat_config.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract host:port C2 address" {
        Has-IOC $script:asyncResult | Should -Be $true
    }

    It "Should contain c2.lab.test in output" {
        $t = Get-AllText $script:asyncResult
        $t | Should -Match 'c2\.lab\.test'
    }
}

Describe "TP: TelegramC2Config" {
    BeforeAll { $script:tgResult = Invoke-MwcpScan (Join-Path $script:TP "telegram_c2.txt") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract bot token as password or URL" {
        ($script:tgResult.password.Count -gt 0 -or
         $script:tgResult.address.Count -gt 0) | Should -Be $true
    }

    It "Should contain 1234567890 bot ID in output" {
        $t = Get-AllText $script:tgResult
        $t | Should -Match '1234567890'
    }
}

Describe "TP: SMTPExfilConfig" {
    BeforeAll { $script:smtpResult = Invoke-MwcpScan (Join-Path $script:TP "smtp_exfil.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract SMTP credential as password" {
        $script:smtpResult.password.Count | Should -BeGreaterThan 0
    }
}

Describe "TP: GenericMutex" {
    BeforeAll { $script:mutexResult = Invoke-MwcpScan (Join-Path $script:TP "generic_mutex.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract hex token as mutex" {
        $script:mutexResult.mutex.Count | Should -BeGreaterThan 0
    }

    It "Should contain A1B2C3D4E5F6 hex token" {
        $t = Get-AllText $script:mutexResult
        $t.ToUpper() | Should -Match 'A1B2C3D4E5F6'
    }
}

Describe "TP: GenericC2" {
    BeforeAll { $script:genC2Result = Invoke-MwcpScan (Join-Path $script:TP "generic_c2.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract 192.0.2.1:4444 as C2 address" {
        $t = Get-AllText $script:genC2Result
        $t | Should -Match '192\.0\.2\.1'
    }
}

Describe "TP: PowerShellDecoder" {
    BeforeAll { $script:psDecResult = Invoke-MwcpScan (Join-Path $script:TP "ps_decoder.ps1") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should decode the -enc payload and extract c2.lab.test" {
        $t = Get-AllText $script:psDecResult
        ($t -match 'c2\.lab\.test' -or $t -match 'DownloadString') | Should -Be $true
    }
}

Describe "TP: LNKParser" {
    BeforeAll { $script:lnkResult = Invoke-MwcpScan (Join-Path $script:TP "lnk_payload.lnk") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract LNK arguments or embedded URL" {
        Has-IOC $script:lnkResult | Should -Be $true
    }

    It "Should contain c2.lab.test from the LNK arguments" {
        $t = Get-AllText $script:lnkResult
        ($t -match 'c2\.lab\.test' -or $t -match 'powershell') | Should -Be $true
    }
}

# ===========================================================================
# FP TESTS -- benign samples must not trigger family-specific parsers
# ===========================================================================
Describe "FP: benign PE has no family-specific config" {
    BeforeAll { $script:fpPeResult = Invoke-MwcpScan (Join-Path $script:FP "benign_pe.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should not contain [CS-Config] in output" {
        $t = Get-AllText $script:fpPeResult
        $t | Should -Not -Match '\[CS-Config\]'
    }

    It "Should not contain [Sliver-Config] in output" {
        $t = Get-AllText $script:fpPeResult
        $t | Should -Not -Match '\[Sliver-Config\]'
    }

    It "Should not contain [NjRAT-Config] in output" {
        $t = Get-AllText $script:fpPeResult
        $t | Should -Not -Match '\[NjRAT-Config\]'
    }
}

Describe "FP: benign PS1 has no encoded command" {
    BeforeAll { $script:fpPs1Result = Invoke-MwcpScan (Join-Path $script:FP "benign_ps1.ps1") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should not emit [PS-EncodedCommand] decoded string" {
        $t = Get-AllText $script:fpPs1Result
        $t | Should -Not -Match '\[PS-EncodedCommand\]'
    }

    It "Should not emit [PoshC2 markers" {
        $t = Get-AllText $script:fpPs1Result
        $t | Should -Not -Match '\[PoshC2'
    }
}

Describe "FP: SMTP reference file has no credential" {
    BeforeAll { $script:fpSmtpResult = Invoke-MwcpScan (Join-Path $script:FP "smtp_reference.txt") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should not extract any password from a reference-only SMTP config" {
        $script:fpSmtpResult.password.Count | Should -Be 0
    }
}

Describe "FP: Log CSV has no NjRAT C2 address" {
    BeforeAll { $script:fpCsvResult = Invoke-MwcpScan (Join-Path $script:FP "log_csv.csv") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should not emit [NjRAT-Config] from log CSV data" {
        $t = Get-AllText $script:fpCsvResult
        $t | Should -Not -Match '\[NjRAT-Config\]'
    }
}

Describe "FP: benign JSON has no C2 framework config" {
    BeforeAll { $script:fpJsonResult = Invoke-MwcpScan (Join-Path $script:FP "benign_json.json") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should not contain Sliver or Merlin config markers" {
        $t = Get-AllText $script:fpJsonResult
        $t | Should -Not -Match '\[Sliver-Config\]|\[Merlin-'
    }

    It "Should not emit Mythic markers" {
        $t = Get-AllText $script:fpJsonResult
        $t | Should -Not -Match '\[Mythic-'
    }
}

Describe "FP: Discord mention without webhook URL" {
    BeforeAll { $script:fpDiscordResult = Invoke-MwcpScan (Join-Path $script:FP "discord_mention.txt") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should not emit Discord-Webhook from plain discord mention text" {
        $t = Get-AllText $script:fpDiscordResult
        $t | Should -Not -Match '\[Discord-Webhook\]'
    }

    It "Should not extract any credential" {
        $script:fpDiscordResult.password.Count | Should -Be 0
    }
}

Describe "FP: Legitimate SMTP email notify script" {
    BeforeAll { $script:fpEmailResult = Invoke-MwcpScan (Join-Path $script:FP "email_notify.ps1") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should not emit AgentTesla markers from a legitimate SMTP script" {
        $t = Get-AllText $script:fpEmailResult
        $t | Should -Not -Match '\[AgentTesla'
    }

    It "Should not extract credentials from the email notify script" {
        $script:fpEmailResult.password.Count | Should -Be 0
    }
}

# TP: New parsers (added after initial 15-parser set)

Describe "TP: DiscordExfilConfig" {
    BeforeAll { $script:discordResult = Invoke-MwcpScan (Join-Path $script:TP "discord_webhook.txt") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract Discord webhook URL" {
        $t = Get-AllText $script:discordResult
        $t | Should -Match 'discord\.com/api/webhooks'
    }

    It "Should include server snowflake ID in output" {
        $t = Get-AllText $script:discordResult
        $t | Should -Match '123456789012345678'
    }
}

Describe "TP: DcRATConfig" {
    BeforeAll { $script:dcratResult = Invoke-MwcpScan (Join-Path $script:TP "dcrat_config.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract C2 address" {
        Has-IOC $script:dcratResult | Should -Be $true
        $script:dcratResult.address | Should -Match 'c2\.lab\.test'
    }

    It "Should emit DcRAT family label" {
        $t = Get-AllText $script:dcratResult
        $t | Should -Match 'DcRAT'
    }
}

Describe "TP: XWormConfig" {
    BeforeAll { $script:xwormResult = Invoke-MwcpScan (Join-Path $script:TP "xworm_config.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract C2 address" {
        Has-IOC $script:xwormResult | Should -Be $true
        $script:xwormResult.address | Should -Match 'c2\.lab\.test'
    }

    It "Should emit XWorm family label" {
        $t = Get-AllText $script:xwormResult
        $t | Should -Match 'XWorm'
    }
}

Describe "TP: QuasarRATConfig" {
    BeforeAll { $script:quasarResult = Invoke-MwcpScan (Join-Path $script:TP "quasarrat_config.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract C2 host:port" {
        Has-IOC $script:quasarResult | Should -Be $true
        $t = Get-AllText $script:quasarResult
        $t | Should -Match 'c2\.lab\.test'
    }

    It "Should extract AES key seed as password" {
        $script:quasarResult.password.Count | Should -BeGreaterThan 0
    }

    It "Should emit Quasar family label with tag" {
        $t = Get-AllText $script:quasarResult
        $t | Should -Match 'Quasar'
        $t | Should -Match 'LabTarget'
    }
}

Describe "TP: AgentTeslaConfig" {
    BeforeAll { $script:atResult = Invoke-MwcpScan (Join-Path $script:TP "agenttesla_config.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract SMTP exfil host as C2 address" {
        $t = Get-AllText $script:atResult
        $t | Should -Match 'smtp\.lab\.test'
    }

    It "Should extract SMTP password" {
        $script:atResult.password.Count | Should -BeGreaterThan 0
    }

    It "Should emit AgentTesla and Keylogger labels" {
        $t = Get-AllText $script:atResult
        $t | Should -Match 'AgentTesla'
        $t | Should -Match 'Keylogger'
    }
}

Describe "TP: AdaptixC2Config" {
    BeforeAll { $script:adaptixResult = Invoke-MwcpScan (Join-Path $script:TP "adaptix_config.bin") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract callback URL as C2 address" {
        $t = Get-AllText $script:adaptixResult
        $t | Should -Match 'c2\.lab\.test'
    }

    It "Should extract agent_id as mutex" {
        $t = Get-AllText $script:adaptixResult
        $t | Should -Match 'AABBCCDD'
    }

    It "Should emit Adaptix family label" {
        $t = Get-AllText $script:adaptixResult
        $t | Should -Match 'Adaptix'
    }
}

Describe "TP: PowGratConfig" {
    BeforeAll { $script:powgratResult = Invoke-MwcpScan (Join-Path $script:TP "powgrat_stager.ps1") }

    It "Should have mwcp available" {
        if (-not $script:MwcpAvailable) { Set-ItResult -Skipped -Because "mwcp not staged" }
        $true | Should -Be $true
    }

    It "Should extract C2Server URL" {
        $t = Get-AllText $script:powgratResult
        $t | Should -Match 'c2\.lab\.test'
    }

    It "Should extract stager password" {
        $script:powgratResult.password.Count | Should -BeGreaterThan 0
    }

    It "Should emit PowGrat family label" {
        $t = Get-AllText $script:powgratResult
        $t | Should -Match 'PowGrat'
    }
}

# ===========================================================================
# Parser source integrity checks
# ===========================================================================
Describe "Parser source: all 22 parsers registered in parser_config.yml" {
    BeforeAll {
        $cfgPath = Join-Path $script:WinHunt "mwcp_parsers\parser_config.yml"
        $script:ParserCfg = if (Test-Path $cfgPath) {
            Get-Content $cfgPath -Raw
        } else { '' }
    }

    $parsers = @(
        'GenericMutex','GenericC2','PowerShellDecoder','LNKParser',
        'TelegramC2Config','CobaltStrikeConfig','SliverConfig',
        'HavocConfig','BruteRatelConfig','MythicConfig','MerlinConfig',
        'PoshC2Config','NjRATConfig','AsyncRATConfig','SMTPExfilConfig',
        'DiscordExfilConfig','DcRATConfig','XWormConfig','QuasarRATConfig',
        'AgentTeslaConfig','AdaptixC2Config','PowGratConfig'
    )

    foreach ($p in $parsers) {
        It "Should have $p registered in parser_config.yml" {
            $script:ParserCfg | Should -Match $p
        }
    }
}

Describe "Parser source: no .file_data attribute usage (silent mwcp 3.x bug)" {
    BeforeAll {
        $parsersDir = Join-Path $script:WinHunt "mwcp_parsers"
        $script:AllParserSrc = Get-ChildItem $parsersDir -Filter "*.py" |
            Get-Content -Raw | Out-String
    }

    It "Should use .data not .file_data (mwcp 3.x API)" {
        $script:AllParserSrc | Should -Not -Match '\.file_data\b'
    }

    It "Should use report.add() not report.get() for metadata" {
        $script:AllParserSrc | Should -Not -Match 'report\.get\(meta\.'
    }
}
